name: create-phar-on-new-tag

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
			
jobs:
  deploy:    
    runs-on: ubuntu-20.04
		steps:
    - name: Setup PHP with PECL extension
    uses: shivammathur/setup-php@v2
    with:
      php-version: '8.2'
      extensions: curl,openssl,mbstring,dom,tidy
      tools: composer:v2
