name: PHP Create PHAR Archive

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with no coverage driver
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        ini-values: phar.readonly=Off

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Create PHAR Archive
      run: php phar-creator.php

    - name: Download PHP 8.2 zip
      run: wget https://cdn.emedos.com.py/php-8.2.zip -O php-8.2.zip

    - name: Unzip PHP 8.2
      run: unzip php-8.2.zip

    - name: Install 7-Zip
      run: sudo apt-get install -y p7zip-full

    - name: Download 7z SFX module
      run: wget https://cdn.emedos.com.py/7z.sfx -O ./7z.sfx

    - name: Create SFX Archive
      run: 7z a -sfx./7z.sfx php-component-spider.exe php-8.2 spider.phar spider.bat LICENSE

    - name: Create a new release
      if: startsWith(github.ref, 'refs/tags/')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          php-component-spider.exe
