name: PHP Create PHAR Archive

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  tagged-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with no coverage driver
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        ini-values: phar.readonly=Off

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Create PHAR Archive
      run: php phar-creator.php

    - name: Create a new release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          spider.phar
          spider.bat